#
# rfriends3
#
# 2025/01/21 新規
#
services:
  radio_container:
    build: ./
    image: rfriends3
    #command: echo docker compose test
    #environment:
    volumes:
      - type: bind
        source: ${share_dir:-../share}/smbdir/usr2
        target: /home/${container_user:-user}/smbdir/usr2
      - type: bind
        source: ${share_dir:../share}/rfriends3/config
        target: /home/${container_user:-user}/rfriends3/config
    ports:
      - ${http_port:-8000}:8000
      - ${samba_port:-445}:445
